### ISSUE TITLE
Input mapping flexível

### ISSUE THREAD

**Issue by DanMargera** [ThePixelThrone/inkreatures#26]
A implementação atual não deixa jogarem 2 players usando teclado e joystick. Porque o mapeamento é fixo:
Device0 e Teclado -> player1
Device1 -> player2
Device2 -> player3
Device3 -> player4

**Comment by haueisen** [comment]
Adicionar também uma tela pra isso.
E adicionar os mapeamento dos botões pros controles que já temos.
